# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Visitor')], default=2, max_length=100),
        ),
    ]
