# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180531_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Visitor')], default=2, max_length=100),
        ),
    ]
