# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-26 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='subTopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.SubTopics'),
        ),
        migrations.AddField(
            model_name='questions',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Topics'),
        ),
    ]
