# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-26 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180526_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='difficultyLevel',
            field=models.CharField(choices=[(1, b'Basic'), (2, b'Mediam'), (3, b'Hard')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[(1, b'subjective'), (2, b'objetive')], max_length=100),
        ),
    ]
