# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180531_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='type',
            new_name='questionType',
        ),
    ]
