# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20180604_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAnswers',
            new_name='QuestionAnswer',
        ),
        migrations.RenameModel(
            old_name='SubTopics',
            new_name='SubTopic',
        ),
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
