# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimages',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
