# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 04:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_auto_20180606_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficultyLevel', models.CharField(choices=[(1, 'Basic'), (2, 'Mediam'), (3, 'Hard')], default=1, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogPosts_author', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogposts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogposts',
            name='topic',
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogImages', to='blogs.BlogPost'),
        ),
        migrations.DeleteModel(
            name='BlogPosts',
        ),
    ]
