# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180531_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=33)),
                ('last_name', models.CharField(max_length=33)),
            ],
        ),
    ]
