# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_persontest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogImages',
            new_name='BlogImage',
        ),
    ]
