# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180607_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='difficultyLevel',
            field=models.CharField(choices=[('1', 'Basic'), ('2', 'Mediam'), ('3', 'Hard')], default='1', max_length=100),
        ),
    ]
